arch/x86/32/common/source/boot.cpp
userspace/libc/src/printf.c

Clang now is able to compile SWEB without errors.
It throws loads of warnings though and SWEB doesn't boot ("Error 13: Invalid or unsupported executable format"), but it's a start I guess. "make emu" works at least! :wink:

Clang build fixes

---

common/source/fs/VfsSyscall.cpp
common/source/fs/minixfs/MinixFSSuperblock.cpp
common/source/fs/minixfs/MinixStorageManager.cpp

Please check if this compiles on Windows before merging.
I assume that the asserts have been forgotten after converting from read() to fread() in 93642d9. However, I might be wrong and they were omitted on purpose.
If this is the case the result of the comparison is never used.
(excuse me for sending the PR twice, but I was told always to base on master, not to incorporate changes from another PR of mine in a second one)

Gly warning cleanup

---

common/include/kernel/Thread.h

CleanupThread implements kill to fire an assertion.
This kill version was not called by the page fault handler since kill in
the parent class was not virtual.

Make Thread::kill virtual to fix bug.

---

arch/x86/64/source/ArchMemory.cpp

getIdentAddressOfPPN was applied to an identity mapping, providing an invalid address

Fix: x86_64 checkAddressValid

---

CMakeLists.txt
arch/arm/common/source/ArchMemory.cpp

The address calculation of ArchMemory::checkAddressValid() provided a wrong ident address.

Fix: ARM memory calculation

---

arch/x86/64/source/ArchMemory.cpp

In the x86_32 implementation, there are PageManager::freePPN calls to free the corresponding physical pages were the PageTables reside. Added appropriate statements to free them in x86_64 too.

x86_64: free PageTable pages if unmapping

---

arch/x86/64/CMakeLists.userspace

Set ld's max page size to 4KB to prevent it from aligning each section
to a 2MB page boundary, making each executable at least 2MB large.
Fixed together with Daniel Kales.

x86_64: Fix large executable files.

---

.gitignore
common/source/util/kstring.cpp

as discussed in #74, implemented a fix for strncmp
also included is a .gitignore entry for the Clion project folder,
since more and more students are using it instead of Eclipse

fixed strncmp bug + gitignore for Clion

---

common/include/fs/devicefs/DeviceFSSuperblock.h
common/source/fs/devicefs/DeviceFSSuperblock.cpp

This fixes a bug where it wasn't possible to delete a file (VfsSyscall::rm(...)), which was previously created by VfsSyscall::open(...).
The problem was that when calling VfsSyscall::close, the default implementation of removeFd of the Superblock base-class was invoked. Because of that, the entry in the list of open files in the RamFSInode wasn't cleared - which subsequently led to the failure of VfsSyscall::rm(...), because the list was not empty.
Steps to reproduce the bug:
- Create file somewhere within devicefs (e.g. /foo.txt) using VfsSyscall::open
- Close the file descriptor using VfsSyscall::close
- Remove the file using VfsSyscall::rm --> this fails

Added DeviceFSSuperblock::removeFd(...)

---

arch/x86/64/source/ArchMemory.cpp

This patch sets the present bit to zero and frees the correct physical page.
I tested this patch with my own sweb project running all the fork/exec/pthread tests.

x86_64: Fixed broken unmapPage method

---

arch/x86/64/source/ArchThreads.cpp

Currently sweb stops with a general protection fault when a userspace program attempts to use floating point instructions in long mode.
The reason for that is that gcc uses the SSE instructions set extension when compiling for x86_64, whereas for x86_32 the traditional FPU instructions are used.
This patch fixes the problem by enabling SSE at boot time.
I tested it with my sleep und usleep syscalls (these syscalls require floating point arithmetic in userspace), they work perfectly accurately after applying this patch.

x86_64: Enable floating point arithmetic

---

arch/x86/32/common/source/InterruptUtils.cpp
arch/x86/64/source/InterruptUtils.cpp

This patch changes two things:
Firstly, it fixes a suspected backtracing bug for x86_32. (wrong if-condition)
Secondly, it prints backtraces for zero page dereferences in kernel mode.
These can be a pain to debug since most of the time sweb crashes at an arbitrary point after killing the current thread or process.
Printing backtraces for this cases shows the root cause of the zero pagefault.
I did this for both x86_32 and x86_64, however it would be nice to have an architecture independent pagefaulthandler class, like we have for the syscall handler.

Fixed backtrace bug, made debugging of unwanted kernel pagefaults easier

---

arch/arm/common/include/offsets.h
arch/x86/32/common/include/offsets.h
arch/x86/32/common/source/InterruptUtils.cpp
arch/x86/64/include/offsets.h
common/source/kernel/Syscall.cpp

I think we should restrict the user space to the lower canonical half, since this allows a clear separation of kernel and user space pointers, similar to other kernels like Linux.
Therefore I set x86_64 USER_BREAK to 0x0000800000000000, the first invalid address above the lower canonical half.

Replaced hardcoded address limits with arch dependent USER_BREAK constant

---

common/include/console/debug.h

this is needed for windows cmdline to reset the color after the tag
also made the tag (e.g [PAGEFAULT ]) bold and the text following it
normal (although that is up for discussion, I think it should be this way round)

changed color codes to reset the color correctly to the default color

---

userspace/libc/include/assert.h

Although I am not sure if we want this in baseline sweb, I think that it would encourage students to write better tests from the beginning on.
I have seen groups that wrote tons of printf()-statements in their tests instead of using assert, which made it impossible to run quick regression tests.
Therefore, having assert in baseline sweb might improve the implementation quality for a lot of groups.

Userspace assert

---

userspace/tests/shell.c

As the title says - shell.c line 30 uses `argsCount > 10` as a condition for breaking out of the loop. For `argsCount == 10`, this does not trigger a break, leading to an out-of-bounds memcpy to `args[10]` in line 45.
Changing the check to `argsCount >= 10` solves the problem.

Fix an array overrun on args if 10 arguments are passed

---

userspace/libc/include/assert.h
userspace/libc/src/printf.c

I added 64 bit support using the `%z` prefix format specifier.
It works with signed and unsigned decimal integers (`%zd`, `%zu`), as well as with hexadecimal integers (`%zx`).
In addition I added support for the `%p` format specifier to make printing pointers more comfortable.
I changed as little code as possible and carried out tests on both `x86_64` and `x86_32` to make sure that nothing gets broken.
(Yet I am unsure whether we should merge this into devel or master, in order to avoid master-changes during the winter term. I also fixed a typo in `assert.h`)

Added 64 bit support for userspace printf

---

common/source/kernel/Syscall.cpp

Correctly suppress sc_outline syscall debug output. Previously used check had no effect because of incorrect comparison and use of boolean 'or' operator.

Fix suppression of debug output for specific syscalls

---

common/source/kernel/Thread.cpp

Setting `switch_to_userspace_ = 0` in Thread::kill() is not required and causes a race condition when Thread::kill() is called on another thread. Removing this unnecessary line of code fixes the race condition.
1. Thread B (in kernel mode, e.g. syscall/pagefault)
* Gets interrupted, registers are saved in Thread B->kernel_registers_ [1]
* Gets scheduled again, return from syscall/pagefault
* Thread B->switch_to_userspace = 1
2. Thread A is scheduled and calls Thread B->kill()
* Thread B->switch_to_userspace_ = 0
3. INTERRUPT 
* Thread B is to be scheduled again
* Scheduler sees Thread B->switch_to_userspace_ == 0
-> currentThreadRegisters = Thread B->kernel_registers_
-> arch_contextSwitch()
4. Thread B->kernel_registers_ still store the state that was saved when Thread B was last …

Fix race condition in Thread::kill()

---

CMakeLists.txt
common/source/kernel/main.cpp
utils/gdbinit

This commit adds some helpers to ease with GDB-debugging sweb.
Compile and run with `./build debug`
Start gdb with `./start_gdb`
`rm -r /tmp/sweb/*` is necessary to switch between versions.

Make SWEB debuggable

---

common/include/ustl/ustringformat.h

Tiny change, fixing the ksprintn declaration in the header to match the implementation in the cpp. 
To make the function call actually work :)

fix ksprintn declaration

---

arch/common/include/Elf32Format.h
arch/common/include/Elf64Format.h

was most probably always true. No changes to Elf32Format.h, as I can't test this currently.

Update Elf64Format.h && Elf32Format.h

---

common/source/fs/ramfs/RamFSFile.cpp
common/source/fs/ramfs/RamFSInode.cpp
common/source/kernel/Syscall.cpp

Fix for #119
(does not fix RamFS file size limitation)

Prevent out-of-bounds read/write in RamFSInode

---

utils/gdbinit

I get the following error on each breakpoint in cgdb:
```
Error while running hook_stop:
Invalid type combination in equality test.
```
It seems that `$eip` is the instruction pointer on 32 bit platforms, while `$pc` works on all platforms gdb supports.
I found this solution on [Stack Overflow](https://stackoverflow.com/questions/9338744/invalid-register-eip). I'm not sure that's the right thing to do, it fixes the error for me though.

Fix an error in gdbinit

---

arch/x86/common/source/ATADriver.cpp
common/include/kernel/Thread.h
common/source/kernel/Scheduler.cpp
common/source/kernel/Thread.cpp
common/source/kernel/UserProcess.cpp

+ Some explanatory comments 
+ Disallow setting the state of other threads to Sleeping (not thread safe) 
+ Sanity check if someone tries to change thread state again after it was already set to ToBeDestroyed
+ Fix leak of Loader in UserProcess constructor when allocation was successful but loading the executable failed

Add checks when setting thread state

---

arch/arm/integratorcp/source/KeyboardManager.cpp

If qemu sends scancode set 1 (like on my machine), the shift key is not released on arm_icp target, because of a too early return statement. (keyboard_status_ variable is not updated)
Fix tested on Ubuntu 14.04 x64 and Ubuntu 16.04 x64.

Fixes arm_icp shift not realeased bug 

---

arch/arm/integratorcp/source/KeyboardManager.cpp
arch/common/include/KeyboardManager.h

I completely fixed scancode stuff, by forcing the selection of scancode set 2, implementing kb_wait, and removing the define which was ran only if scancode set 2 was assumed on arm_icp target...
Should work on older and newer qemu hosts without the define now...
Tested on my machine (Ubuntu 14.04 x64) and a Tutors machine (Debian which used to send the other scancode set by default).

Completely fixed scancode stuff on arm_icp

---

userspace/libc/src/printf.c

It is now aware of the long format specifier.. (e.g. %lu did not work...)

Fixed userspace printf implementation

---

userspace/libc/src/scanf.c
userspace/tests/shell.c

According to the posix standard `gets` should have this behaviour:
> The gets() function shall read bytes from the standard input stream, stdin, into the array pointed to by s, until a \<newline\> is read or an end-of-file condition is encountered. Any \<newline\> shall be discarded and a null byte shall be placed immediately after the last byte read into the array.
The implementation before misses a check for EOF and a newline is also not replaced with a null byte.
Unfortunately this breaks the current implementation of the shell but I fixed them too.

made gets posix compatible and fixed caused bugs in shell

---

common/include/fs/FileSystemInfo.h
common/source/fs/PathWalker.cpp
common/source/fs/VfsSyscall.cpp
common/source/kernel/Thread.cpp
userspace/libc/src/printf.c
utils/exe2minixfs/exe2minixfs.cpp
utils/exe2minixfs/types.h

There's currently a contraption called `FakeThread` in `exe2minixfs` to enable natively compiling outside the context of SWEB.
It's also really ugly and unnecessary. So I'm replacing it with a `getcwd()` method.

Exterminate FakeThread with extreme prejudice

---

userspace/libc/include/assert.h

The expression being asserted is currently being included as a string literal in the printf format specifier. This means that any printf format sequences in the expression (such as the modulo operator `%`) will be interpreted and may lead to unexpected behavior.
This PR changes the asserted expression to instead be passed as a string parameter, avoiding this issue.

Ignore printf specifiers in assert statements

---

arch/x86/32/common/include/ArchThreads.h
arch/x86/32/common/source/ArchThreads.cpp
arch/x86/64/include/ArchThreads.h
arch/x86/64/source/ArchThreads.cpp

* Remove dpl and ss0 from ArchThreadRegisters on x86
* Cleanup x86 64bit thread register creation to be the same as on 32bit

Remove unused entries from ArchThreadRegisters + cleanup x86_64 thread register creation

---

utils/add-debug/dwarf/CMakeLists.txt
utils/add-debug/elf/CMakeLists.txt

Generate required `to_string.cc` file in cmake build. Fixes https://github.com/IAIK/sweb/commit/f50c40e0a87b02b31b0cbb7b926a3d440650180e#r27386483
Additionally, `to_string.cc` is now generated out-of-tree instead of in the source folder.
Copying `enum-print.py` to `BIN_DIR/../elf/` is fairly ugly, but that's how it's required by the library Makefile...

Fix cmake add-debug build

---

arch/arm/common/include/ArchMemory.h
arch/arm/common/source/ArchMemory.cpp
arch/x86/32/include/ArchMemory.h
arch/x86/32/pae/include/ArchMemory.h
arch/x86/32/pae/source/ArchMemory.cpp
arch/x86/32/source/ArchMemory.cpp
arch/x86/64/include/ArchMemory.h
arch/x86/64/source/ArchMemory.cpp
arch/x86/64/source/boot.32.C
common/source/kernel/Loader.cpp

mapPage() support for mapping large pages is unused + unmapPage() doesn't support unmapping large pages in any case
Also fixes a page leak on ARM when a process is destroyed

Remove unused code for mapping large pages

---

arch/arm/common/source/ArchMemory.cpp
arch/x86/32/pae/source/ArchMemory.cpp
arch/x86/32/source/ArchMemory.cpp

Apparently I missed that in the last commit.
Also changed unmapPage() for ARM and x86_32_pae to assert when page is not mapped (matches behavior of x86_64 and x86_32).

Remove large page support from x86_32_pae unmapPage()

---

arch/x86/64/source/ArchMemory.cpp

Selecting an option with resolution at startup, the assert in ArchMemory.cpp:235 would fail an cause a kernel panic.

Fixed crash when selecting boot option with resolution

---

CMakeLists.txt

This fixes an oversight in 0f5a67c00ae811c0a9298e2d240b06169bf29916 that caused x86/32 to not build successfully.

Fix x86/32 build

---

common/include/console/debug.h

To ensure kprintf() is automatically visible when using debug(). 
Currently using debug() requires including both debug.h and kprintf.h
(In most cases it's included somewhere in other include files, but not when e.g. working in a completely new file that only includes debug.h and no other header files)

Include kprintf in debug.h

---

common/source/kernel/Loader.cpp

The check only hides the problem but doesn't actually solve it. Removing the check should make it more obvious that the problem exists.

Remove check in loadPage whether page is already present

---

userspace/libc/include/sys/mman.h
userspace/libc/src/mman.c

Since mprotect has now been added to tacos we should also add an implementation stub and the header declaration.

Add mprotect stub

---

arch/x86/32/common/source/ArchCommon.cpp
arch/x86/64/source/ArchCommon.cpp
arch/x86/common/include/multiboot.h
common/source/mm/PageManager.cpp

* Multiboot mmap info
* Read full 64-bit memory addresses
* Use size field to iterate over structs (struct size is not guaranteed to be constant)
* Use a bitfield for the multiboot info flags
* Copy module names (32bit)
* Some debug output changes in PageManager

Multiboot changes

---

arch/x86/64/source/boot.32.C
common/include/ustl/sistream.h
common/include/ustl/sostream.h
common/include/ustl/uatomic.h
common/include/ustl/uios.h
common/source/ustl/sostream.cpp

We need `fmtflags` as a struct for the overloads not to conflict.
Also, some functions were defined twice

fix build for GCC 8

---

arch/x86/64/source/boot.32.C

The volatile qualifier is somehow ignored in function arguments, so I moved it to a variable.
Correctly compiles on -O1 (and incidentally also on -O2 and -O3).
[godbolt link](https://godbolt.org/g/rqgPhF)

Fix TRUNCATE macro for -O1

---

common/source/console/TextConsole.cpp

Don't clear status row when scrolling the console. Prevents flickering and keeps the status row visible when printing lots of text.

Keep status row on screen

---

common/include/console/debug.h

changed the debug message BACKTRACE from Ansi_Red to Ansi_Cyan.

Updated debug.h

---

common/source/console/Console.cpp

This commit allows the selection of terminal 2 (if multiple terminals are enabled).
Previously this was not possible, because there is a skipped keycode between F1 and F2 (F1 == 0x80, F2 == 0x82).

fix terminal selection

---

arch/armv8/common/source/ArchMemory.cpp

Added a missing "checkAndRemove" call in the armv8 unmapPage function, which lead to a possible double free.

armv8 ArchMemory unmapPage: missing "checkAndRemove" for page table level 1 entry

---

common/source/fs/VfsSyscall.cpp

`fs_info->pathname_.c_str()` can be `NULL` when the FileSystemInfo object
has already been destroyed (e.g. when copied incorrectly on fork).
Leads to hard-to-debug errors at `fs_info->pathname_ = "./";`

Debug checks in VfsSyscall::dupChecking()

---

common/include/mm/KernelMemoryManager.h
common/source/mm/KernelMemoryManager.cpp

This pull requests changes the marker_ value in the kernel memory manager from `0xdeadbeef` to `0xdeadbeef ^ this`.
With this change the KMM now detects bugs that look like
```c
void *a = kmalloc(512);
void *b = kmalloc(512);
memcpy(a, b, 528);
```
Previously this would have lead to an endless loop in the KMM, because the `next_` and `prev_` pointers changed while the marker_ stayed the same.

make KMM marker position dependent

---

arch/armv8/common/source/ArchMemory.cpp
common/source/util/kstring.cpp

Fixed wrong copy order of the kernel memmove which lead to problems with overlapping buffers.

Kernel memmove wrong way around

---

common/include/ustl/ualgobase.h
common/include/ustl/utypes.h

HAVE_CPP11 and HAVE_CPP14 are defined in config.h depending on compiler-provided defines to detect C++11 and C++14 support.
The current codebase never includes this header, and therefore assumes C++11 is not supported, meaning `ustl::unique_ptr`, `ustl::shared_ptr`, and other C++11 and later features cannot be used.
Including the header somehow also defines HAVE_CPP14 on new enough compilers, meaning the broken duplicate implementation of `ustl::exchange` needed to be fixed as well.
This fixes `ustl::unique_ptr` and `ustl::shared_ptr`.

ustl: include config.h so that HAVE_CPP* are correctly defined and fix exchange

---

common/source/kernel/Loader.cpp

forgot to delete stab_data and stabstr_data when "SWEBDbg Infos are empty"

memory leak in Loader::loadDebugInfoIfAvailable

---

common/source/console/FrameBufferConsole.cpp
common/source/console/Terminal.cpp
common/source/console/TextConsole.cpp

Thanks to #208 and #209 we have a working memmove implementation; now we can actually use it.

refactor terminal scroll up

---

common/include/ustl/uqueue.h

Currently, compilation fails with the error `uqueue.h:15:44: error: ‘vector’ does not name a type
template <typename T, typename Container = vector<T> >` when only the file `uqueue.h` without `uvector.h` is included.

Include uvector.h in uqueue.h

---

common/source/util/kstring.cpp

Calls to `itoa` https://github.com/IAIK/sweb/blob/a559148a2c6cba69f88ce0043736b8cec2059252/common/source/util/kstring.cpp#L496 with base 16 printed strange, non-hex characters.

itoa now correctly converts with base 16

---

common/include/fs/File.h
common/include/fs/Inode.h
common/source/fs/VfsSyscall.cpp
common/source/fs/minixfs/MinixFSFile.cpp
common/source/fs/ramfs/RamFSFile.cpp
userspace/libc/include/fcntl.h
utils/exe2minixfs/exe2minixfs.cpp

This PR adds a correct flag check for `VfsSyscall::open`. It now compares with existing flags instead of checking whether the passed flag exceeded a constant. This also adds a NYI error for the flags `O_TRUNC` and `O_APPEND`.
The file open `#define`s now match between user- and kernelspace.
This also moves the files fs permissions (i.e. `i_mode_`) from `File.h` to `Inode.h`.

Vfs flag fixes

---

userspace/libc/src/printf.c

Fixes #201 
Due to a negation mistake in the right-align code, character_count sometimes got increased to over 256 by a subtraction of negative numbers.
printf now correctly truncates.

Fix printf for strings >256 chars

---

common/source/mm/KernelMemoryManager.cpp

use the following (e.g. in main.cpp) to reproduce the bug:
```
auto kmm = KernelMemoryManager::instance();
pointer p1 = kmm->allocateMemory(PAGE_SIZE*2, 0);
pointer p2 = kmm->allocateMemory(PAGE_SIZE*2, 0);
kmm->freeMemory(p1, 0);
kmm->freeMemory(p2, 0);
```
from the commit:
> When enabling the DYNAMIC_KMM, a call to the freeSegment method
> possibly removes the page, where the KMM saved the segment.
> Any further access may lead to a page fault and subsequently to
> a kernel panic.
> 
> For example, allocating two buffers (p1and p2) of at least the
> size of PAGE_SIZE allocates at least two pages (assuming no
> memory on the heap is free).
> Freeing p1 does nothing because memory after p1 is not free.
> Then freeing p2 leads to a call to ksbrk that unmaps the page of
> p2, including its …

Fix use-after-free in KMM

---

arch/x86/64/CMakeLists.include

This adds two missing target, `net` and `net-init` to the x86_64 Makefile.

net and net-init targets for x86_64

---

arch/x86/32/common/source/InterruptUtils.cpp
arch/x86/64/source/InterruptUtils.cpp
common/include/util/kstring.h
common/source/mm/PageManager.cpp
common/source/util/kstring.cpp

\+ detect page faults caused by invalid use of reserved bits

Use-after-free detection for PPNs

---

arch/x86/64/include/paging-definitions.h

Add static asserts for x86_64 paging definitions to make it impossible to compile sweb with paging definitions with a size not equal to 8 bytes.

add static assert for paging definitions

---

arch/x86/64/include/ArchMemory.h

Remove ArchMemory::getIdentAddress because of possible confusion with ArchMemory::getIdentAddressOfPPN.

remove ArchMemory::getIdentAddress

---

userspace/libc/include/sys/mman.h

MAP_PRIVATE should not be 0, because 0 cannot be checked when combined with other flags. 
- found with Timst3r

change MAP_PRIVATE to 0x20000000 to be checkable

---

common/source/kernel/Mutex.cpp

Add locking checks for acquiring a mutex for the case where we don't need to sleep.

add locking checks for mutex

---

common/include/util/Bitmap.h
common/source/util/Bitmap.cpp

Add copy constructor that does a deep copy of the bitmap. This will probably save a few future OS students some debugging time :)

Add copy constructor for Bitmap utility class

---

CMakeLists.txt
arch/arm/verdex/utils/makeflash.sh
utils/images/resize_power2.sh

- Resize disk image to next power of two (required when used as an sd card in newer qemu versions)
https://www.mail-archive.com/qemu-devel@nongnu.org/msg723028.html
This does not actually increase the size of the disk image file since we are using the qcow2 file format.
- Add a debug check in the arm verdex build scripts to check if the kernel image fits inside the available flash space on the board
(This currently fails and I suspect it has been failing for a long time now. ARM verdex support for SWEB is not in a great shape.)

Resize disk image to next power of two + error check for arm verdex build

---

arch/x86/64/CMakeLists.include

Change kvm target to use host cpu instead of the legacy kvm64 cpu.
This change should also make nested virtualization possible using the kvm target.

change legacy qemu kvm64 cpu to host

---

arch/x86/64/source/init_boottime_pagetables.cpp

Using the identity mapping to remove the identity mapping is probably not a good idea.
Probably only worked because it is very unlikely that the TLB gets flushed between line 108 and 109

x86_64 fix boot time caching issue

---

arch/x86/64/source/ArchThreads.cpp

[ArchThreads::atomic_add]: Fix for missing precision

---

common/include/fs/Inode.h
common/source/fs/Inode.cpp
common/source/fs/PathWalker.cpp
common/source/fs/minixfs/MinixFSInode.cpp
common/source/fs/minixfs/MinixFSSuperblock.cpp

CI build complains about local variable being visible across case labels. Add blocks to reduce scope of variable.
(Warning didn't show up locally for some reason but does in CI)
\+ make inode refcount non-atomic to fix arm build (ustl::atomic doesn't work properly on arm #257 )

Fix CI build warning + ARM build

---

common/source/kernel/Thread.cpp

Having an assert in a function that gets called by assert is probably a bad idea.

update BACKTRACE_MAX_FRAMES assert

---

common/include/kernel/Thread.h

Having the kernel stack below the pointers to the stored registers leads to problems when detecting stack overflows.

update kernel stack placement

---

common/source/kernel/Condition.cpp
common/source/mm/PageFaultHandler.cpp

Many students do not see CVs as something that could produce deadlocks. While holding locks when waiting on a CV is not a bug in itself in a lot of cases, it is either unnecessary or extremely slow. I am also done with people completely ignoring the warning even when it eventually leads to a deadlock (which happens in most cases where this warning is printed).
This PR also uncomments the register dump line in the PF handler per default since it does not hurt and is, in general, very useful.

Add condition variable assert

---

arch/arm/integratorcp/CMakeLists.include
arch/arm/rpi2/CMakeLists.include
arch/x86/32/CMakeLists.include
arch/x86/32/pae/CMakeLists.include
arch/x86/64/CMakeLists.include

Some GCC versions (e.g. 11.1.0) complain about wrong format string arguments when printing values of bit fields:
`debug(SYSCALL, "PPN is: %zd\n", m.pt[m.pti].page_ppn);`
`warning: format ‘%zd’ expects argument of type ‘signed size_t’, but argument 2 has type ‘int’ [-Wformat=]`
Older compilers allow this.
A quick google search didn't come up with a way to make newer compilers behave like older ones in this regard, so this pull request changes this error to a warning to allow people with newer compilers to at least compile the code with warnings.

Only warn on format string errors to account for compiler version differences

---

arch/x86/64/CMakeLists.include
common/source/kernel/main.cpp
utils/gdbinit

\+ Start qemu x86_64 in paused mode to allow debugger to connect (matching all other architectures)

Use actual gdb breakpoint at startup instead of pseudo software breakpoint

---

arch/arm/integratorcp/CMakeLists.userspace
arch/arm/rpi2/CMakeLists.userspace
arch/armv8/rpi3/CMakeLists.userspace
arch/x86/32/CMakeLists.userspace
arch/x86/32/pae/CMakeLists.userspace
arch/x86/64/CMakeLists.userspace

On some gcc versions on Ubuntu the stack clash protection is enabled per default leading to confusion when testing growing stacks and swapping with large stack arrays in SWEB. As found by Mario Bischof the compiler flag -fno-stack-clash-protection explicitly disables that feature. In this pull request, it is added to the compilation flags of all supported architectures.

explicitly disabling stack clash protection

---

arch/x86/64/CMakeLists.userspace

gcc 11 uses dwarf5 debug info by default. The libelfin library used for the `add-dbg` utility can only handle up to dwarf4.

Fix userspace debug info for gcc >= 11

---

common/source/kernel/Syscall.cpp

pseudols with kernel memory addresses prints the data at that address. Added a check to prevent that.

fixed arbitrary kernel read in pseudols

---

arch/x86/32/common/source/SegmentUtils.cpp
arch/x86/64/source/boot.32.C

Changed segment granularity for the TSS from page size to byte granularity.
The I/O map base address in the TSS was set to 0 which made it possible for ring 3 code to execute in/out instructions with most ports (including PIC, disk i/o, qemu debug, ...).

fix tss size and io base

---

common/source/fs/minixfs/MinixFSInode.cpp

When rounding the size in MinixFSInode write to the next multiple of ZONE_SIZE, an integer overflow can occur.
This results in the allocation of a too-small heap buffer and a subsequent heap buffer overflow when copying the user space data to the kernel buffer.

fix heap buffer overflow in MinixFSInode write

---

common/include/ustl/uttraits.h

Fix compilation on GCC 13
https://github.com/IAIK/sweb/issues/292

Use __is_convertible builtin in ustl when available

---

arch/x86/64/CMakeLists.include
arch/x86/64/source/ArchCommon.cpp
arch/x86/64/source/boot.32.C

Enable SMEP on x86_64 if it is available.
Add some clobbers to the boot code assembly.

Enable SMEP

---

utils/add-debug/elf/data.hh

`set_binding` is declared as a const member function when it changes the member variable `this->info`. 
```cpp
void set_binding(stb v) const
{
info = (info & 0xF) | ((unsigned char)v << 4);
}
```
As the struct is a template it compiled pre-gcc14,  now gcc14+ is capable of throwing an error in this case too:
```cpp
// Detected by gcc 14
template<typename T>
class A {
int b;
void set() const {
this->b = 1;
}
};
// Detected by gcc 13 and gcc 14
class B {
int b;
void set() const {
this->b = 1;
}
};
```
https://godbolt.org/z/qW5j7WoaK
```
[ecomaikgolf@laptop ~/sweb/]$ git rev-parse --short HEAD
4f2a6230
[ecomaikgolf@laptop ~/sweb/]$ git status --porcelain    
?? build/
[ecomaikgolf@laptop ~/sweb/]$ make -C build 
make: Entering directory '/home/ecomaikgolf/sweb/build'
....
In file included …
```

fix compiler error in gcc 14

---

arch/arm/integratorcp/source/KeyboardManager.cpp
arch/common/include/KeyboardManager.h
arch/x86/common/source/KeyboardManager.cpp
common/include/console/Terminal.h
common/source/console/Console.cpp
common/source/console/Terminal.cpp

Using underscores in test names is pretty common.
Now that sweb has tab completion, you can select tests with underscores in their name without having to type them.
Which lead to groups being confused why the tortillas test runner cannot run their tests.
So I thought it would be good to make underscores typeable by default.
Instead of remapping the keys with `Terminal::remap`, this introduces a shift map based on the US layout.
So other characters like `:"|<>?+` are also typeable.
If this is not desirable, I would propose to just add underscores to the remap function like [this](https://github.com/PaideiaDilemma/tortillas-sweb/commit/f39b7edb406764026622f555927b08e84db0e3fc).
Idk about the rpi2 and rpi3 implementations, their E0 map is weird, so I did not even touch that.
This will break …

Add shift keymap

---

common/include/fs/Inode.h
common/include/fs/devicefs/DeviceFSSuperblock.h
common/source/fs/devicefs/DeviceFSSuperblock.cpp
common/source/fs/devicefs/DeviceFSType.cpp

Most occurrences of Superblock are already written with a lowercase b (including the filename).
Now all Superblocks are written with lowercase b.

Fixed `Superblock` naming inconsistency

---

arch/armv8/common/source/InterruptUtils.cpp

The previous value was a permission fault on level 3. Present is now 0 when a translation fault occurs on any level, and 1 if not. This now mirrors the x86 implementation.

ARMv8: Corrected present value in page fault handler

---

arch/arm/rpi2/include/board_constants.h
arch/arm/rpi2/source/debug_bochs.cpp

Could be done in a better location during initial boot, but this fixes the debug output on rpi2.

Enable PL011 UART peripheral on rpi2

---

common/include/kernel/Scheduler.h
common/source/kernel/Scheduler.cpp

Introduced a debug warning in the scheduler to log when the cleanup thread
has not finished cleaning up all threads marked for destruction before it
is descheduled. This ensures that any unfinished cleanup work is flagged,
helping to identify potential issues with thread management or incomplete 
cleanup processes in the system.

add debug warning when cleanup thread is not finished

---

arch/x86/32/include/paging-definitions.h

Fixed a static assert in the 32bit paging definitions, which was probably a typo in 79a484183f3d3c9664ed523a2b16aa0e874ff298

fixed a wrong static_assert
