- arch/arm/integratorcp/CMakeLists.include
- arch/arm/rpi/CMakeLists.include
- arch/arm/verdex/CMakeLists.include
- arch/x86/32/CMakeLists.include
- arch/x86/32/pae/CMakeLists.include
- arch/x86/64/CMakeLists.include
- utils/exe2minixfs/CMakeLists.txt
+ remove suppression of deprecation warnings
+ align flags
> cmake flag cleanup

- arch/arm/integratorcp/CMakeLists.include
- arch/arm/rpi/CMakeLists.include
- arch/arm/verdex/CMakeLists.include
- arch/x86/32/CMakeLists.include
- arch/x86/32/pae/CMakeLists.include
- arch/x86/64/CMakeLists.include
Includes disabling of automatic reboot, `gnu11` for ARM builds, improved console texts and cleanup of `CMakeLists.include`s.
> Improve cmakelists include

- arch/x86/32/common/source/InterruptUtils.cpp
reported by Thomas Bohnstingl, Franz Scherr and Nikolaus Kopp
> fixed wrong flag in pageFaultHandler

- common/source/fs/BDVirtualDevice.cpp
Added some additional assertions for reading and writing data to a block device. Prevents memory corruption by checking for  out of range errors.
> * Added some additional assertions for reading and writing data

- arch/x86/64/source/ArchMemory.cpp
Added missing line to archmemory destructor
> x86_64: Fixed page map level 4 memory leak

- userspace/libc/src/printf.c
This patch adds support for %f and %F to the libc printf. Precision and padding are also supported.
> added floating point support to libc printf

- CMakeLists.txt
- arch/x86/64/source/ArchCommon.cpp
Also fixes framebuffer mode on 64bit.
> Set default arch to x86/64

- .gitignore
- arch/arm/integratorcp/CMakeLists.include
- arch/arm/rpi/CMakeLists.include
- arch/arm/verdex/CMakeLists.include
- arch/x86/32/CMakeLists.include
- arch/x86/32/pae/CMakeLists.include
- arch/x86/64/CMakeLists.include
also added debug binaries to .gitignore
> added -Wno-nonnull-compare to disable warnings for assert(this)

- userspace/libc/include/pthread.h
- userspace/libc/include/wait.h
i messed the old pull request up, so i created a new one ^^
> changed relevant datatypes to always fit the architecture

- common/source/kernel/Condition.cpp
The thread calling Condition::wait() releases the waiters list lock and then sets its state to sleeping, but the condition could be signaled after the lock has been released but before the thread could go to sleep. Condition::signal() checks if the state of the thread is Sleeping and if not (as in this case), asserts.
The check if the thread to be woken up is actually sleeping is not necessary, since Scheduler::wake() waits until the thread is actually sleeping before waking it up again.
The clearing of the lock_waiting_on_ variable can be moved to the wait function to be cleared by the sleeping thread itself after it has been woken up.
(Mutex works the same way)
> Fix faulty assumption about thread state when waking up thread in condition variable

- arch/x86/64/source/ArchCommon.cpp
The existing condition with && doesn't do anything and it probably should have been a binary &
> Fixed flag check

- userspace/libc/include/stdio.h
- userspace/libc/src/scanf.c
added two functions to `stdio.h`:
- `char *fgets(char *str, int num, int fd)`
- `int sscanf(const char *buffer, const char *fmt, ...)`
> added sscanf and fgets functions

- userspace/libc/src/printf.c
Current `printf` logic can only handle a single prefix specifier (`0zl+-`), and only before the width specifier. This causes valid placeholders such as `%08zx` to not be interpreted properly.
This PR rectifies this by allowing multiple prefix specifiers, and correctly parsing them both before and after the width.
It also cleans up some incorrect (outdated) comments in `printf` code.
> Handle multiple prefix specifiers in printf

- utils/CMakeLists.txt
Fixes https://github.com/IAIK/sweb/pull/147#issuecomment-364596914
Not sure how I missed this. A proper fix would be a sane handling of build environments.
> Fix utils build when building for arm

- arch/x86/32/common/source/ArchCommon.cpp
- arch/x86/64/source/ArchCommon.cpp
- common/include/mm/PageManager.h
- common/source/mm/PageManager.cpp
As suggested by @fkirc 
Also adds Fx info/stats to x86_32/pae
> Add number of free pages to heartbeat stats

- common/source/kernel/Scheduler.cpp
1 Improve performance to avoid system lockups
~2 Prioritize cleanup thread when a certain number of dead threads has accumulated~
> Improve scheduler

- common/include/kernel/Thread.h
- common/source/console/panic.cpp
- common/source/kernel/Thread.cpp
- common/source/kernel/UserProcess.cpp
Clarification that it's about the kernel stack, not the user stack
> Rename getStackStartPointer function

- common/source/fs/minixfs/MinixFSInode.cpp
Bug found by Kevin Pretterhofer
> correct size for write back buffer

- common/source/mm/KernelMemoryManager.cpp
> Fix KMM misalignment issue; fixes #161

- userspace/libc/src/string.c
memset should return the destination parameter
> Fix memset return value

- common/source/fs/minixfs/MinixStorageManager.cpp
- common/source/util/Bitmap.cpp
and clean up bitmap constructor
> Fix: num_zones instead of num_inodes in MinixStorageManager::flush

- arch/x86/64/source/boot.32.C
> Fix build on gcc Debian 8.2.0-14

- common/source/util/kstring.cpp
Fixed kernel memmove off by one error.
> Kernel memmove off by one

- arch/x86/64/source/boot.32.C
(cherry pick from my SWEB version)
> Fix segment descriptor limits (real hardware/kvm compatibility)

- .travis.yml
- CMakeLists.txt
- arch/arm/integratorcp/CMakeLists.include
- arch/arm/rpi2/CMakeLists.include
- arch/arm/verdex/CMakeLists.include
- arch/armv8/rpi3/CMakeLists.include
- arch/x86/32/CMakeLists.include
- arch/x86/32/pae/CMakeLists.include
- arch/x86/64/CMakeLists.include
- utils/travis_test.sh
Not yet sure if this breaks things in the test system (expected image path changes)
> Use qcow2 instead of raw image format

- CMakeLists.txt
Support for https://www.gdbgui.com/
> Add gdbgui debug run command

- arch/arm/common/source/IDEDriver.cpp
- arch/armv8/common/source/IDEDriver.cpp
- arch/x86/common/source/IDEDriver.cpp
Those spaces ripped apart the nice kernel console.
> remove spaces after linebreaks... SANITY!

- arch/arm/common/source/assert.cpp
- arch/armv8/common/source/assert.cpp
- arch/x86/common/source/assert.cpp
- common/include/console/panic.h
- common/include/ustl/ustring.h
- common/include/ustl/utypes.h
- userspace/libc/include/assert.h
- userspace/tests/CMakeLists.txt
A few minor fixes:
- Fixed missing debug info for userspace tests in subfolders.
- Fixed incorrect signed int limits in utypes.h
- Use file:line format to help IDE navigation, see e.g. [VSCode terminal links](https://code.visualstudio.com/docs/terminal/basics#_links)
> QoL adjustments

- common/source/kernel/Loader.cpp
Fix a typo in a Loader's debug message
> Fix a typo

- arch/x86/32/common/source/ArchCommon.cpp
- arch/x86/64/source/ArchCommon.cpp
Show Heartbeat and Stats in VESA-Consoles.
> Added Stats and Heartbeat to VESA Consols (x86/64)
